"""Self-contained affective lexicons + tokenizer for the lean deterministic stack.

These back the adapters when ``vaderSentiment`` / ``nrclex`` are not installed. They are
intentionally small but cover common lived-experience vocabulary. Swapping in the real
libraries is a drop-in adapter change (the port seam), with zero changes above
``infrastructure/``.
"""

from __future__ import annotations

import re

_TOKEN_RE = re.compile(r"[a-zA-Z']+")


def tokenize(text: str) -> list[str]:
    return [t.lower() for t in _TOKEN_RE.findall(text)]


def sentences(text: str) -> list[tuple[int, int, str]]:
    """Split into (start, end, text) sentence spans on . ! ? and newlines."""
    spans: list[tuple[int, int, str]] = []
    start = 0
    for m in re.finditer(r"[^.!?\n]+[.!?\n]?", text):
        seg = m.group(0)
        if seg.strip():
            spans.append((m.start(), m.end(), seg.strip()))
        start = m.end()
    if not spans and text.strip():
        spans.append((0, len(text), text.strip()))
    return spans


# Valence lexicon: word -> polarity in [-1, 1]
VALENCE: dict[str, float] = {
    # positive
    "happy": 0.8,
    "joy": 0.85,
    "joyful": 0.85,
    "glad": 0.6,
    "grateful": 0.75,
    "love": 0.9,
    "loved": 0.85,
    "loving": 0.8,
    "hope": 0.6,
    "hoping": 0.55,
    "hopeful": 0.7,
    "excited": 0.7,
    "delighted": 0.8,
    "proud": 0.7,
    "calm": 0.5,
    "peaceful": 0.6,
    "relieved": 0.6,
    "relief": 0.6,
    "content": 0.6,
    "safe": 0.5,
    "secure": 0.5,
    "wonderful": 0.85,
    "great": 0.7,
    "good": 0.5,
    "better": 0.4,
    "warm": 0.5,
    "trust": 0.6,
    "connected": 0.6,
    "alive": 0.6,
    "free": 0.55,
    "thankful": 0.75,
    "amazing": 0.85,
    "beautiful": 0.7,
    "enjoy": 0.7,
    "enjoyed": 0.7,
    "comfort": 0.55,
    # negative
    "sad": -0.7,
    "sadness": -0.75,
    "unhappy": -0.7,
    "depressed": -0.85,
    "down": -0.45,
    "afraid": -0.7,
    "fear": -0.75,
    "scared": -0.75,
    "anxious": -0.7,
    "anxiety": -0.75,
    "worried": -0.6,
    "worry": -0.6,
    "nervous": -0.55,
    "angry": -0.8,
    "anger": -0.8,
    "furious": -0.9,
    "frustrated": -0.65,
    "hurt": -0.7,
    "pain": -0.7,
    "painful": -0.7,
    "lonely": -0.7,
    "alone": -0.4,
    "empty": -0.65,
    "lost": -0.6,
    "hopeless": -0.9,
    "helpless": -0.8,
    "ashamed": -0.7,
    "shame": -0.7,
    "guilt": -0.65,
    "guilty": -0.65,
    "tired": -0.4,
    "exhausted": -0.6,
    "overwhelmed": -0.7,
    "stuck": -0.55,
    "broken": -0.75,
    "grief": -0.8,
    "loss": -0.65,
    "disgust": -0.75,
    "disgusted": -0.75,
    "contempt": -0.65,
    "contemptuous": -0.65,
    "corrupt": -0.7,
    "degrading": -0.7,
    "repugnant": -0.75,
    "recoil": -0.45,
    "unethical": -0.6,
    "immoral": -0.65,
    "vile": -0.8,
    "sleazy": -0.65,
    "hate": -0.85,
    "terrible": -0.8,
    "awful": -0.8,
    "bad": -0.5,
    "worse": -0.55,
    "fail": -0.6,
    "failure": -0.7,
    "cry": -0.6,
    "crying": -0.65,
    "numb": -0.5,
    "dread": -0.75,
    "regret": -0.6,
    "bracing": -0.45,
    "braced": -0.45,
    "brace": -0.4,
    "worse": -0.55,
}

# Multiword phrase valence (scanned in addition to single words) -> polarity in [-1, 1]
PHRASE_VALENCE: dict[str, float] = {
    "fall apart again": -0.8,
    "fall apart": -0.7,
    "falling apart": -0.72,
    "get better": 0.55,
    "getting better": 0.55,
    "the worst": -0.6,
    "expecting the worst": -0.7,
    "let go": 0.3,
    "at peace": 0.55,
    "give up": -0.6,
    "shut down": -0.55,
    "cannot stand": -0.55,
    "can't stand": -0.55,
    "turn away": -0.45,
    "pull back": -0.4,
    "disengage": -0.4,
    "not be part": -0.45,
    "cutting corners": -0.5,
}

# High-arousal words -> arousal contribution in [0,1]
AROUSAL: dict[str, float] = {
    "furious": 0.95,
    "panic": 0.95,
    "terrified": 0.95,
    "rage": 0.9,
    "excited": 0.8,
    "thrilled": 0.85,
    "anxious": 0.75,
    "nervous": 0.65,
    "scared": 0.75,
    "afraid": 0.7,
    "angry": 0.8,
    "overwhelmed": 0.8,
    "shaking": 0.8,
    "racing": 0.8,
    "frantic": 0.9,
    "stressed": 0.7,
    "worried": 0.6,
    "alarmed": 0.8,
    "shocked": 0.8,
    "ecstatic": 0.9,
    "calm": 0.1,
    "peaceful": 0.1,
    "numb": 0.15,
    "tired": 0.2,
    "exhausted": 0.25,
    "quiet": 0.2,
    "still": 0.2,
    "settled": 0.2,
    "drained": 0.25,
    "bracing": 0.6,
    "braced": 0.55,
    "dread": 0.7,
}

# Power / dominance / control words -> dominance contribution in [0,1]
DOMINANCE: dict[str, float] = {
    "control": 0.8,
    "decide": 0.75,
    "decided": 0.75,
    "will": 0.6,
    "can": 0.65,
    "strong": 0.75,
    "capable": 0.75,
    "confident": 0.8,
    "choose": 0.7,
    "manage": 0.7,
    "powerful": 0.85,
    "ready": 0.65,
    "determined": 0.8,
    "helpless": 0.1,
    "powerless": 0.05,
    "trapped": 0.1,
    "stuck": 0.2,
    "can't": 0.2,
    "cannot": 0.2,
    "weak": 0.2,
    "overwhelmed": 0.15,
    "lost": 0.25,
    "out": 0.4,
}

# NRC-like emotion lexicon: emotion -> set of words
EMOTION_LEXICON: dict[str, set[str]] = {
    "joy": {
        "happy",
        "joy",
        "joyful",
        "glad",
        "delighted",
        "excited",
        "thrilled",
        "grateful",
        "thankful",
        "wonderful",
        "enjoy",
        "enjoyed",
        "proud",
        "amazing",
        "funny",
        "hilarious",
        "laugh",
        "laughed",
        "laughing",
        "amusing",
        "amused",
    },
    "love": {"love", "loved", "loving", "adore", "cherish", "warm", "connected", "close"},
    "trust": {"trust", "safe", "secure", "reliable", "faith", "believe", "support"},
    "sadness": {
        "sad",
        "sadness",
        "unhappy",
        "depressed",
        "down",
        "lonely",
        "empty",
        "grief",
        "loss",
        "cry",
        "crying",
        "hopeless",
        "broken",
        "lost",
        "regret",
    },
    "fear": {
        "afraid",
        "fear",
        "scared",
        "anxious",
        "anxiety",
        "worried",
        "worry",
        "nervous",
        "dread",
        "terrified",
        "panic",
        "alarmed",
        "uneasy",
        "threat",
        "bracing",
        "braced",
    },
    "anger": {
        "angry",
        "anger",
        "furious",
        "rage",
        "frustrated",
        "annoyed",
        "resent",
        "resentment",
        "irritated",
        "mad",
        "hate",
    },
    "disgust": {
        "disgust",
        "disgusted",
        "sick",
        "revolted",
        "gross",
        "repulsed",
        "repulse",
        "repulsion",
        "aversion",
        "nauseated",
        "nausea",
        "stomach",
        "repugnant",
        "vile",
        "sleazy",
        "nauseating",
    },
    "moral_aversion": {
        "recoil",
        "contempt",
        "contemptuous",
        "corrupt",
        "corruption",
        "degrading",
        "degraded",
        "unethical",
        "immoral",
        "repugnant",
        "sleazy",
        "vile",
        "disengage",
        "disgusting",
    },
    "surprise": {
        "surprised",
        "shocked",
        "amazed",
        "astonished",
        "unexpected",
        "sudden",
        "stunned",
        "startled",
        "startle",
    },
    "wonder": {"wonder", "wondering", "awe", "marvel", "marveled", "marvelled", "astounding"},
    "anticipation": {
        "hope",
        "hopeful",
        "expect",
        "waiting",
        "anticipate",
        "looking",
        "forward",
        "soon",
        "future",
        "will",
    },
}

# Multi-word phrase -> emotion (scanned in addition to token hits in emotion_evidence).
PHRASE_EMOTION_LEXICON: dict[str, list[str]] = {
    "moral_aversion": [
        "turn away",
        "cannot stand",
        "can't stand",
        "pull back",
        "disengage",
        "not be part",
        "cutting corners",
        "will not be part",
        "refuse to participate",
        "quiet recoil",
    ],
    "disgust": [
        "cannot stand",
        "can't stand",
    ],
}
