-- Fix AFF rows in svarupa_concept_layer (Multi-Axis Affect Analysis applicability).
--
-- **Superseded** — do not run the legacy INSERT below. Use instead:
--
--   PYTHONPATH=src python scripts/seed_concept_layer_from_excel.py
--     (source: documentation/dimensions_and_concepts/*.xlsx)
--
-- Repair from exported snapshot (includes ``role`` column):
--
--   PYTHONPATH=src python scripts/export_aff_concept_layer.py
--   PYTHONPATH=src python scripts/fix_aff_concept_layer.py
--
-- Verify:
--   SELECT cl.dimension_id, d.slug, cl.role, COUNT(*) AS n
--     FROM svarupa_concept_layer cl
--     JOIN svarupa_dimensions d ON d.dimension_id = cl.dimension_id
--    WHERE cl.layer_code = 'AFF'
--    GROUP BY cl.dimension_id, d.slug, cl.role
--    ORDER BY cl.dimension_id, cl.role;
